### ISSUE TITLE
Connection Error: Backend Service Unavailable

### ISSUE THREAD

**Issue by ameenalasady** [Pushan2005/SpotTransfer#1]
I encountered an issue when attempting to connect to transfer playlists. Here are the details:  

1. **Steps to Reproduce:**  
   - Followed the instructions to obtain YouTube Music request headers.  
   - Clicked on "Connect" in the SpotTransfer tool.  

2. **Observed Behavior:**  
   - Error message:  
     `Connection error. Please try again: TypeError: NetworkError when attempting to fetch resource.`  

   - Checking network requests revealed:  
     - A 503 status for `https://spottransfer-backend.onrender.com/` with the response:  
       `Response body is not available to scripts (Reason: CORS Missing Allow Origin)`  
     - Visiting `https://spottransfer-backend.onrender.com/` directly displays:  
       `This service has been suspended.` 

The project looks great, and I'd love to use it! Please let me know if there’s any workaround or plan to restore the backend service.

**Comment by Pushan2005** [comment]
Hey, 

![Screenshot_2024-12-27-07-49-06-97_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/user-attachments/assets/a83aac4b-1714-4400-a3af-ba7f754d7b10)

I wasn't expecting this to get so much usage, I'll have this sorted in a couple days. I don't have access to my laptop at the moment.

**Comment by Pushan2005** [comment]
I should be up and running again

**Comment by ameenalasady** [comment]
Thanks for the update. I'm still experiencing the same issue. Perhaps the backend service got suspended again?

**Comment by Jayc965** [comment]
This issue still persists.
